from __future__ import annotations

from pathlib import Path

from .data_contract import ARTIFACT_COLUMN_METADATA, RAW_COLUMN_METADATA
from .io_utils import _atomic_write


def build_data_dictionary_markdown() -> str:
    lines = [
        "# Data Dictionary",
        "",
        "Generated from schema contracts in `src/sales_analytics/data_contract.py`.",
        "",
        "## Raw Dataset",
        "",
        "| Column | Definition | Expected Type | Quality Rule |",
        "|---|---|---|---|",
    ]

    for column, metadata in RAW_COLUMN_METADATA.items():
        lines.append(
            f"| {column} | {metadata['definition']} | {metadata['type']} | {metadata['quality_rule']} |"
        )

    lines.extend(["", "## Curated Artifacts", ""])

    for artifact_name, columns in ARTIFACT_COLUMN_METADATA.items():
        lines.extend(
            [
                f"### `{artifact_name}`",
                "",
                "| Column | Definition | Expected Type | Quality Rule |",
                "|---|---|---|---|",
            ]
        )
        for column, metadata in columns.items():
            lines.append(
                f"| {column} | {metadata['definition']} | {metadata['type']} | {metadata['quality_rule']} |"
            )
        lines.append("")

    lines.extend(
        [
            "## Notes",
            "",
            "- Core analysis columns: `ORDERDATE`, `SALES`.",
            "- Main concentration dimensions: `PRODUCTLINE`, `CUSTOMERNAME`, `COUNTRY`.",
            "- Curated artifacts are regenerated by the official batch pipeline.",
            "",
        ]
    )
    return "\n".join(lines)


def export_data_dictionary(output_path: Path) -> Path:
    return _atomic_write(
        output_path,
        lambda tmp: tmp.write_text(build_data_dictionary_markdown(), encoding="utf-8"),
    )
